db:
  host: 'localhost'
  usernname: 'postgres'
  password: 'postgres'
  synchronize: true

jwt:
  secret: 'topSecret51'

email:
  verificationEnabled: false
  apiKey: ''
  domain: 'mail.shargea.com'
  from: 'Shargea <noreply@shargea.com>'
  hostname: 'http://localhost:3000'
